In [56]:
#importing pandas library for file manipulation
import pandas as pd

In [57]:
#importing numpy library for numerical manipulation
import numpy as np

In [58]:
#loading dataset into workspace
df=pd.read_csv(r"C:\Users\ashib\Downloads\electric_car_dataset_15000_rows.csv")
df

,Company,Model,Country_of_Purchase,Mileage_per_Charge_Miles,Battery_kWh,Price_USD,Units_Sold,Customer_Rating_Out_of_5,Recommended_for_Use
0,Audi,Q4 e-tron,Netherlands,416,94,30121,79177,4.6,Yes
1,Kia,EV6,Canada,302,86,92561,26861,3.1,No
2,Tesla,Model S,Norway,388,94,75804,118634,3.0,No
3,Tesla,Model X,Australia,403,41,82422,105939,4.3,Yes
4,Nissan,Leaf,UAE,307,71,34323,102312,3.7,No
...,...,...,...,...,...,...,...,...,...
14995,Audi,Q4 e-tron,UK,358,89,37984,69019,3.5,No
14996,BMW,i3,Australia,263,118,94242,144096,3.6,No
14997,Mercedes,EQA,India,205,43,26161,83327,3.7,No
14998,MG,MG4 EV,UK,399,73,94902,19683,4.8,Yes
14999,BYD,Dolphin,China,267,71,80206,114984,3.9,No

In [59]:
#checking for data information like type and size all
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Company                   15000 non-null  object
 1   Model                     15000 non-null  object
 2   Country_of_Purchase       15000 non-null  object
 3   Mileage_per_Charge_Miles  15000 non-null  int64
 4   Battery_kWh               15000 non-null  int64
 5   Price_USD                 15000 non-null  int64
 6   Units_Sold                15000 non-null  int64
 7   Customer_Rating_Out_of_5  15000 non-null  float64
 8   Recommended_for_Use       15000 non-null  object
dtypes: float64(1), int64(4), object(4)
memory usage: 1.0+ MB

In [60]:
#checking is there any null values present or not
df.isnull().sum()

Company                     0
Model                       0
Country_of_Purchase         0
Mileage_per_Charge_Miles    0
Battery_kWh                 0
Price_USD                   0
Units_Sold                  0
Customer_Rating_Out_of_5    0
Recommended_for_Use         0
dtype: int64

In [61]:
#coverting recommend for use to numeric datatype by using yes for 1 and no for 0
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["Recommended_for_Use"] = le.fit_transform(df["Recommended_for_Use"])

In [62]:
#checking the dataset changed or not
df

,Company,Model,Country_of_Purchase,Mileage_per_Charge_Miles,Battery_kWh,Price_USD,Units_Sold,Customer_Rating_Out_of_5,Recommended_for_Use
0,Audi,Q4 e-tron,Netherlands,416,94,30121,79177,4.6,1
1,Kia,EV6,Canada,302,86,92561,26861,3.1,0
2,Tesla,Model S,Norway,388,94,75804,118634,3.0,0
3,Tesla,Model X,Australia,403,41,82422,105939,4.3,1
4,Nissan,Leaf,UAE,307,71,34323,102312,3.7,0
...,...,...,...,...,...,...,...,...,...
14995,Audi,Q4 e-tron,UK,358,89,37984,69019,3.5,0
14996,BMW,i3,Australia,263,118,94242,144096,3.6,0
14997,Mercedes,EQA,India,205,43,26161,83327,3.7,0
14998,MG,MG4 EV,UK,399,73,94902,19683,4.8,1
14999,BYD,Dolphin,China,267,71,80206,114984,3.9,0

In [63]:
#input and output deciding
x=df[['Mileage_per_Charge_Miles','Battery_kWh','Price_USD','Units_Sold','Customer_Rating_Out_of_5']]
y=df['Recommended_for_Use']

In [64]:
#splitting dagtaset for training and testing set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [65]:
#training using a model
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [66]:
#predicting pred = model.
pred=model.predict(X_test)

In [67]:
#finding accuracy
from sklearn.metrics import r2
accuracy=accuracy_score(X_train,X_test)

ValueError: Found input variables with inconsistent numbers of samples: [10500, 4500]